apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
spec:
  template:
    spec:
      containers:
      - name: server
        env:
        - name: DISABLE_STATS
          value: "1"
        - name: DISABLE_TRACING
          value: "1"
